#jasypt:
##  encryptor:
##    password: su2020

server:
  port: 8888
  servlet:
    context-path: /s
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml




